# Generated by Django 5.1 on 2025-12-31 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
