# Generated by Django 5.1 on 2025-12-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
    ]
