# Generated by Django 5.1 on 2026-01-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakApp', '0002_streak_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
