# Generated by Django 5.1 on 2025-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakApp', '0002_completion_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='color',
            field=models.CharField(default='red', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
