# Generated by Django 5.1 on 2025-12-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakApp', '0003_streak_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose'), ('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone')], max_length=255, unique=True),
        ),
    ]
