# Generated by Django 5.1 on 2026-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent_important', 'Urgent & Important'), ('urgent_not_important', 'Urgent, Not Important'), ('not_urgent_important', 'Not Urgent, Important'), ('not_urgent_not_important', 'Not Urgent, Not Important')], default='urgent_important', help_text='Eisenhower matrix quadrant.', max_length=32),
        ),
    ]
