// This file is auto-generated by @hey-api/openapi-ts

import { type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

// NOTE:
// - SDK endpoints already include `/api/...` in their `url` field.
// - Default to same-origin so deployed builds call the current domain.
// - Override if needed (e.g. local dev without nginx): VITE_API_BASE_URL=http://localhost:8002
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? '';

export const client = createClient(createConfig<ClientOptions2>({ baseUrl }));
