// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * One active question paired with its answer for a given date (if any).
 */
export type CheckinItem = {
    question_id: number;
    text: string;
    order: number;
    answer_id: number | null;
    answer: string;
};

/**
 * * `red` - Red
 * * `orange` - Orange
 * * `amber` - Amber
 * * `yellow` - Yellow
 * * `lime` - Lime
 * * `green` - Green
 * * `emerald` - Emerald
 * * `teal` - Teal
 * * `cyan` - Cyan
 * * `sky` - Sky
 * * `blue` - Blue
 * * `indigo` - Indigo
 * * `violet` - Violet
 * * `purple` - Purple
 * * `fuchsia` - Fuchsia
 * * `pink` - Pink
 * * `rose` - Rose
 * * `slate` - Slate
 * * `gray` - Gray
 * * `zinc` - Zinc
 * * `neutral` - Neutral
 * * `stone` - Stone
 */
export type ColorEnum = 'red' | 'orange' | 'amber' | 'yellow' | 'lime' | 'green' | 'emerald' | 'teal' | 'cyan' | 'sky' | 'blue' | 'indigo' | 'violet' | 'purple' | 'fuchsia' | 'pink' | 'rose' | 'slate' | 'gray' | 'zinc' | 'neutral' | 'stone';

export type Completion = {
    readonly id: number;
    date_completed: string;
    day_of_week?: number;
    streak: number;
};

export type DailyAnswer = {
    readonly id: number;
    question: number;
    readonly question_text: string;
    date: string;
    /**
     * Markdown supported.
     */
    answer?: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type Idea = {
    readonly id: number;
    /**
     * The idea.
     */
    content: string;
    /**
     * Where you heard it / what you were doing when the idea came.
     */
    source: string;
    created_at?: string;
    readonly updated_at: string;
};

export type Log = {
    readonly id: number;
    /**
     * Markdown supported.
     */
    body: string;
    created_at?: string;
    readonly updated_at: string;
};

export type PatchedCompletion = {
    readonly id?: number;
    date_completed?: string;
    day_of_week?: number;
    streak?: number;
};

export type PatchedDailyAnswer = {
    readonly id?: number;
    question?: number;
    readonly question_text?: string;
    date?: string;
    /**
     * Markdown supported.
     */
    answer?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
};

export type PatchedIdea = {
    readonly id?: number;
    /**
     * The idea.
     */
    content?: string;
    /**
     * Where you heard it / what you were doing when the idea came.
     */
    source?: string;
    created_at?: string;
    readonly updated_at?: string;
};

export type PatchedLog = {
    readonly id?: number;
    /**
     * Markdown supported.
     */
    body?: string;
    created_at?: string;
    readonly updated_at?: string;
};

export type PatchedQuestion = {
    readonly id?: number;
    text?: string;
    is_active?: boolean;
    order?: number;
    readonly created_at?: string;
};

export type PatchedStreak = {
    readonly id?: number;
    readonly completions?: Array<Completion>;
    readonly current_streak?: number;
    readonly longest_streak?: number;
    readonly days_completed?: number;
    name?: string;
    is_active?: boolean;
    start_date?: string;
    color?: ColorEnum;
    description?: string | null;
    user?: number;
};

export type PatchedTask = {
    readonly id?: number;
    title?: string;
    /**
     * Markdown supported.
     */
    description?: string;
    /**
     * Time you expect to spend on this.
     */
    expected_minutes?: number | null;
    /**
     * Time you actually spent.
     */
    actual_minutes?: number | null;
    status?: StatusEnum;
    /**
     * Eisenhower matrix quadrant.
     *
     * * `urgent_important` - Urgent & Important
     * * `urgent_not_important` - Urgent, Not Important
     * * `not_urgent_important` - Not Urgent, Important
     * * `not_urgent_not_important` - Not Urgent, Not Important
     */
    priority?: PriorityEnum;
    started_at?: string | null;
    completed_at?: string | null;
    created_at?: string;
    readonly updated_at?: string;
};

/**
 * Serializer for User model with Google OAuth fields.
 */
export type PatchedUser = {
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    google_id?: string | null;
    google_email?: string | null;
    google_picture?: string | null;
    readonly google_access_token?: string;
    readonly google_refresh_token?: string;
    google_token_expiry?: string | null;
    readonly date_joined?: string;
    /**
     * Active
     *
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active?: boolean;
};

/**
 * * `urgent_important` - Urgent & Important
 * * `urgent_not_important` - Urgent, Not Important
 * * `not_urgent_important` - Not Urgent, Important
 * * `not_urgent_not_important` - Not Urgent, Not Important
 */
export type PriorityEnum = 'urgent_important' | 'urgent_not_important' | 'not_urgent_important' | 'not_urgent_not_important';

export type Question = {
    readonly id: number;
    text: string;
    is_active?: boolean;
    order?: number;
    readonly created_at: string;
};

/**
 * * `todo` - To do
 * * `in_progress` - In progress
 * * `done` - Done
 */
export type StatusEnum = 'todo' | 'in_progress' | 'done';

export type Streak = {
    readonly id: number;
    readonly completions: Array<Completion>;
    readonly current_streak: number;
    readonly longest_streak: number;
    readonly days_completed: number;
    name: string;
    is_active?: boolean;
    start_date: string;
    color: ColorEnum;
    description?: string | null;
    user?: number;
};

export type Task = {
    readonly id: number;
    title: string;
    /**
     * Markdown supported.
     */
    description?: string;
    /**
     * Time you expect to spend on this.
     */
    expected_minutes?: number | null;
    /**
     * Time you actually spent.
     */
    actual_minutes?: number | null;
    status?: StatusEnum;
    /**
     * Eisenhower matrix quadrant.
     *
     * * `urgent_important` - Urgent & Important
     * * `urgent_not_important` - Urgent, Not Important
     * * `not_urgent_important` - Not Urgent, Important
     * * `not_urgent_not_important` - Not Urgent, Not Important
     */
    priority?: PriorityEnum;
    started_at?: string | null;
    completed_at?: string | null;
    created_at?: string;
    readonly updated_at: string;
};

/**
 * Serializer for User model with Google OAuth fields.
 */
export type User = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    google_id?: string | null;
    google_email?: string | null;
    google_picture?: string | null;
    readonly google_access_token: string;
    readonly google_refresh_token: string;
    google_token_expiry?: string | null;
    readonly date_joined: string;
    /**
     * Active
     *
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active: boolean;
};

export type CompletionWritable = {
    date_completed: string;
    day_of_week?: number;
    streak: number;
};

export type DailyAnswerWritable = {
    question: number;
    date: string;
    /**
     * Markdown supported.
     */
    answer?: string;
};

export type IdeaWritable = {
    /**
     * The idea.
     */
    content: string;
    /**
     * Where you heard it / what you were doing when the idea came.
     */
    source: string;
    created_at?: string;
};

export type LogWritable = {
    /**
     * Markdown supported.
     */
    body: string;
    created_at?: string;
};

export type PatchedCompletionWritable = {
    date_completed?: string;
    day_of_week?: number;
    streak?: number;
};

export type PatchedDailyAnswerWritable = {
    question?: number;
    date?: string;
    /**
     * Markdown supported.
     */
    answer?: string;
};

export type PatchedIdeaWritable = {
    /**
     * The idea.
     */
    content?: string;
    /**
     * Where you heard it / what you were doing when the idea came.
     */
    source?: string;
    created_at?: string;
};

export type PatchedLogWritable = {
    /**
     * Markdown supported.
     */
    body?: string;
    created_at?: string;
};

export type PatchedQuestionWritable = {
    text?: string;
    is_active?: boolean;
    order?: number;
};

export type PatchedStreakWritable = {
    name?: string;
    is_active?: boolean;
    start_date?: string;
    color?: ColorEnum;
    description?: string | null;
    user?: number;
};

export type PatchedTaskWritable = {
    title?: string;
    /**
     * Markdown supported.
     */
    description?: string;
    /**
     * Time you expect to spend on this.
     */
    expected_minutes?: number | null;
    /**
     * Time you actually spent.
     */
    actual_minutes?: number | null;
    status?: StatusEnum;
    /**
     * Eisenhower matrix quadrant.
     *
     * * `urgent_important` - Urgent & Important
     * * `urgent_not_important` - Urgent, Not Important
     * * `not_urgent_important` - Not Urgent, Important
     * * `not_urgent_not_important` - Not Urgent, Not Important
     */
    priority?: PriorityEnum;
    started_at?: string | null;
    completed_at?: string | null;
    created_at?: string;
};

/**
 * Serializer for User model with Google OAuth fields.
 */
export type PatchedUserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    google_id?: string | null;
    google_email?: string | null;
    google_picture?: string | null;
    google_token_expiry?: string | null;
};

export type QuestionWritable = {
    text: string;
    is_active?: boolean;
    order?: number;
};

export type StreakWritable = {
    name: string;
    is_active?: boolean;
    start_date: string;
    color: ColorEnum;
    description?: string | null;
    user?: number;
};

export type TaskWritable = {
    title: string;
    /**
     * Markdown supported.
     */
    description?: string;
    /**
     * Time you expect to spend on this.
     */
    expected_minutes?: number | null;
    /**
     * Time you actually spent.
     */
    actual_minutes?: number | null;
    status?: StatusEnum;
    /**
     * Eisenhower matrix quadrant.
     *
     * * `urgent_important` - Urgent & Important
     * * `urgent_not_important` - Urgent, Not Important
     * * `not_urgent_important` - Not Urgent, Important
     * * `not_urgent_not_important` - Not Urgent, Not Important
     */
    priority?: PriorityEnum;
    started_at?: string | null;
    completed_at?: string | null;
    created_at?: string;
};

/**
 * Serializer for User model with Google OAuth fields.
 */
export type UserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    google_id?: string | null;
    google_email?: string | null;
    google_picture?: string | null;
    google_token_expiry?: string | null;
};

export type CheckinRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date to fetch the check-in for (YYYY-MM-DD). Defaults to today.
         */
        date?: string;
    };
    url: '/api/checkin/';
};

export type CheckinRetrieveResponses = {
    200: Array<CheckinItem>;
};

export type CheckinRetrieveResponse = CheckinRetrieveResponses[keyof CheckinRetrieveResponses];

export type CompletionsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/completions/';
};

export type CompletionsListResponses = {
    200: Array<Completion>;
};

export type CompletionsListResponse = CompletionsListResponses[keyof CompletionsListResponses];

export type CompletionsCreateData = {
    body: CompletionWritable;
    path?: never;
    query?: never;
    url: '/api/completions/';
};

export type CompletionsCreateResponses = {
    201: Completion;
};

export type CompletionsCreateResponse = CompletionsCreateResponses[keyof CompletionsCreateResponses];

export type CompletionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this completion.
         */
        id: number;
    };
    query?: never;
    url: '/api/completions/{id}/';
};

export type CompletionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CompletionsDestroyResponse = CompletionsDestroyResponses[keyof CompletionsDestroyResponses];

export type CompletionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this completion.
         */
        id: number;
    };
    query?: never;
    url: '/api/completions/{id}/';
};

export type CompletionsRetrieveResponses = {
    200: Completion;
};

export type CompletionsRetrieveResponse = CompletionsRetrieveResponses[keyof CompletionsRetrieveResponses];

export type CompletionsPartialUpdateData = {
    body?: PatchedCompletionWritable;
    path: {
        /**
         * A unique integer value identifying this completion.
         */
        id: number;
    };
    query?: never;
    url: '/api/completions/{id}/';
};

export type CompletionsPartialUpdateResponses = {
    200: Completion;
};

export type CompletionsPartialUpdateResponse = CompletionsPartialUpdateResponses[keyof CompletionsPartialUpdateResponses];

export type CompletionsUpdateData = {
    body: CompletionWritable;
    path: {
        /**
         * A unique integer value identifying this completion.
         */
        id: number;
    };
    query?: never;
    url: '/api/completions/{id}/';
};

export type CompletionsUpdateResponses = {
    200: Completion;
};

export type CompletionsUpdateResponse = CompletionsUpdateResponses[keyof CompletionsUpdateResponses];

export type DailyAnswersListData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        question?: number;
    };
    url: '/api/daily-answers/';
};

export type DailyAnswersListResponses = {
    200: Array<DailyAnswer>;
};

export type DailyAnswersListResponse = DailyAnswersListResponses[keyof DailyAnswersListResponses];

export type DailyAnswersCreateData = {
    body: DailyAnswerWritable;
    path?: never;
    query?: never;
    url: '/api/daily-answers/';
};

export type DailyAnswersCreateResponses = {
    201: DailyAnswer;
};

export type DailyAnswersCreateResponse = DailyAnswersCreateResponses[keyof DailyAnswersCreateResponses];

export type DailyAnswersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this daily answer.
         */
        id: number;
    };
    query?: never;
    url: '/api/daily-answers/{id}/';
};

export type DailyAnswersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DailyAnswersDestroyResponse = DailyAnswersDestroyResponses[keyof DailyAnswersDestroyResponses];

export type DailyAnswersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this daily answer.
         */
        id: number;
    };
    query?: never;
    url: '/api/daily-answers/{id}/';
};

export type DailyAnswersRetrieveResponses = {
    200: DailyAnswer;
};

export type DailyAnswersRetrieveResponse = DailyAnswersRetrieveResponses[keyof DailyAnswersRetrieveResponses];

export type DailyAnswersPartialUpdateData = {
    body?: PatchedDailyAnswerWritable;
    path: {
        /**
         * A unique integer value identifying this daily answer.
         */
        id: number;
    };
    query?: never;
    url: '/api/daily-answers/{id}/';
};

export type DailyAnswersPartialUpdateResponses = {
    200: DailyAnswer;
};

export type DailyAnswersPartialUpdateResponse = DailyAnswersPartialUpdateResponses[keyof DailyAnswersPartialUpdateResponses];

export type DailyAnswersUpdateData = {
    body: DailyAnswerWritable;
    path: {
        /**
         * A unique integer value identifying this daily answer.
         */
        id: number;
    };
    query?: never;
    url: '/api/daily-answers/{id}/';
};

export type DailyAnswersUpdateResponses = {
    200: DailyAnswer;
};

export type DailyAnswersUpdateResponse = DailyAnswersUpdateResponses[keyof DailyAnswersUpdateResponses];

export type IdeasListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
    url: '/api/ideas/';
};

export type IdeasListResponses = {
    200: Array<Idea>;
};

export type IdeasListResponse = IdeasListResponses[keyof IdeasListResponses];

export type IdeasCreateData = {
    body: IdeaWritable;
    path?: never;
    query?: never;
    url: '/api/ideas/';
};

export type IdeasCreateResponses = {
    201: Idea;
};

export type IdeasCreateResponse = IdeasCreateResponses[keyof IdeasCreateResponses];

export type IdeasDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this idea.
         */
        id: number;
    };
    query?: never;
    url: '/api/ideas/{id}/';
};

export type IdeasDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type IdeasDestroyResponse = IdeasDestroyResponses[keyof IdeasDestroyResponses];

export type IdeasRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this idea.
         */
        id: number;
    };
    query?: never;
    url: '/api/ideas/{id}/';
};

export type IdeasRetrieveResponses = {
    200: Idea;
};

export type IdeasRetrieveResponse = IdeasRetrieveResponses[keyof IdeasRetrieveResponses];

export type IdeasPartialUpdateData = {
    body?: PatchedIdeaWritable;
    path: {
        /**
         * A unique integer value identifying this idea.
         */
        id: number;
    };
    query?: never;
    url: '/api/ideas/{id}/';
};

export type IdeasPartialUpdateResponses = {
    200: Idea;
};

export type IdeasPartialUpdateResponse = IdeasPartialUpdateResponses[keyof IdeasPartialUpdateResponses];

export type IdeasUpdateData = {
    body: IdeaWritable;
    path: {
        /**
         * A unique integer value identifying this idea.
         */
        id: number;
    };
    query?: never;
    url: '/api/ideas/{id}/';
};

export type IdeasUpdateResponses = {
    200: Idea;
};

export type IdeasUpdateResponse = IdeasUpdateResponses[keyof IdeasUpdateResponses];

export type LogsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
    url: '/api/logs/';
};

export type LogsListResponses = {
    200: Array<Log>;
};

export type LogsListResponse = LogsListResponses[keyof LogsListResponses];

export type LogsCreateData = {
    body: LogWritable;
    path?: never;
    query?: never;
    url: '/api/logs/';
};

export type LogsCreateResponses = {
    201: Log;
};

export type LogsCreateResponse = LogsCreateResponses[keyof LogsCreateResponses];

export type LogsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this log.
         */
        id: number;
    };
    query?: never;
    url: '/api/logs/{id}/';
};

export type LogsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type LogsDestroyResponse = LogsDestroyResponses[keyof LogsDestroyResponses];

export type LogsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this log.
         */
        id: number;
    };
    query?: never;
    url: '/api/logs/{id}/';
};

export type LogsRetrieveResponses = {
    200: Log;
};

export type LogsRetrieveResponse = LogsRetrieveResponses[keyof LogsRetrieveResponses];

export type LogsPartialUpdateData = {
    body?: PatchedLogWritable;
    path: {
        /**
         * A unique integer value identifying this log.
         */
        id: number;
    };
    query?: never;
    url: '/api/logs/{id}/';
};

export type LogsPartialUpdateResponses = {
    200: Log;
};

export type LogsPartialUpdateResponse = LogsPartialUpdateResponses[keyof LogsPartialUpdateResponses];

export type LogsUpdateData = {
    body: LogWritable;
    path: {
        /**
         * A unique integer value identifying this log.
         */
        id: number;
    };
    query?: never;
    url: '/api/logs/{id}/';
};

export type LogsUpdateResponses = {
    200: Log;
};

export type LogsUpdateResponse = LogsUpdateResponses[keyof LogsUpdateResponses];

export type QuestionsListData = {
    body?: never;
    path?: never;
    query?: {
        is_active?: boolean;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
    url: '/api/questions/';
};

export type QuestionsListResponses = {
    200: Array<Question>;
};

export type QuestionsListResponse = QuestionsListResponses[keyof QuestionsListResponses];

export type QuestionsCreateData = {
    body: QuestionWritable;
    path?: never;
    query?: never;
    url: '/api/questions/';
};

export type QuestionsCreateResponses = {
    201: Question;
};

export type QuestionsCreateResponse = QuestionsCreateResponses[keyof QuestionsCreateResponses];

export type QuestionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this question.
         */
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}/';
};

export type QuestionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type QuestionsDestroyResponse = QuestionsDestroyResponses[keyof QuestionsDestroyResponses];

export type QuestionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this question.
         */
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}/';
};

export type QuestionsRetrieveResponses = {
    200: Question;
};

export type QuestionsRetrieveResponse = QuestionsRetrieveResponses[keyof QuestionsRetrieveResponses];

export type QuestionsPartialUpdateData = {
    body?: PatchedQuestionWritable;
    path: {
        /**
         * A unique integer value identifying this question.
         */
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}/';
};

export type QuestionsPartialUpdateResponses = {
    200: Question;
};

export type QuestionsPartialUpdateResponse = QuestionsPartialUpdateResponses[keyof QuestionsPartialUpdateResponses];

export type QuestionsUpdateData = {
    body: QuestionWritable;
    path: {
        /**
         * A unique integer value identifying this question.
         */
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}/';
};

export type QuestionsUpdateResponses = {
    200: Question;
};

export type QuestionsUpdateResponse = QuestionsUpdateResponses[keyof QuestionsUpdateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type StreaksListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streaks/';
};

export type StreaksListResponses = {
    200: Array<Streak>;
};

export type StreaksListResponse = StreaksListResponses[keyof StreaksListResponses];

export type StreaksCreateData = {
    body: StreakWritable;
    path?: never;
    query?: never;
    url: '/api/streaks/';
};

export type StreaksCreateResponses = {
    201: Streak;
};

export type StreaksCreateResponse = StreaksCreateResponses[keyof StreaksCreateResponses];

export type StreaksDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this streak.
         */
        id: number;
    };
    query?: never;
    url: '/api/streaks/{id}/';
};

export type StreaksDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type StreaksDestroyResponse = StreaksDestroyResponses[keyof StreaksDestroyResponses];

export type StreaksRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this streak.
         */
        id: number;
    };
    query?: never;
    url: '/api/streaks/{id}/';
};

export type StreaksRetrieveResponses = {
    200: Streak;
};

export type StreaksRetrieveResponse = StreaksRetrieveResponses[keyof StreaksRetrieveResponses];

export type StreaksPartialUpdateData = {
    body?: PatchedStreakWritable;
    path: {
        /**
         * A unique integer value identifying this streak.
         */
        id: number;
    };
    query?: never;
    url: '/api/streaks/{id}/';
};

export type StreaksPartialUpdateResponses = {
    200: Streak;
};

export type StreaksPartialUpdateResponse = StreaksPartialUpdateResponses[keyof StreaksPartialUpdateResponses];

export type StreaksUpdateData = {
    body: StreakWritable;
    path: {
        /**
         * A unique integer value identifying this streak.
         */
        id: number;
    };
    query?: never;
    url: '/api/streaks/{id}/';
};

export type StreaksUpdateResponses = {
    200: Streak;
};

export type StreaksUpdateResponse = StreaksUpdateResponses[keyof StreaksUpdateResponses];

export type StreaksMyStreaksListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streaks/my_streaks/';
};

export type StreaksMyStreaksListResponses = {
    200: Array<Streak>;
};

export type StreaksMyStreaksListResponse = StreaksMyStreaksListResponses[keyof StreaksMyStreaksListResponses];

export type TasksListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * * `todo` - To do
         * * `in_progress` - In progress
         * * `done` - Done
         */
        status?: 'done' | 'in_progress' | 'todo';
    };
    url: '/api/tasks/';
};

export type TasksListResponses = {
    200: Array<Task>;
};

export type TasksListResponse = TasksListResponses[keyof TasksListResponses];

export type TasksCreateData = {
    body: TaskWritable;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type TasksCreateResponses = {
    201: Task;
};

export type TasksCreateResponse = TasksCreateResponses[keyof TasksCreateResponses];

export type TasksDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}/';
};

export type TasksDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type TasksDestroyResponse = TasksDestroyResponses[keyof TasksDestroyResponses];

export type TasksRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}/';
};

export type TasksRetrieveResponses = {
    200: Task;
};

export type TasksRetrieveResponse = TasksRetrieveResponses[keyof TasksRetrieveResponses];

export type TasksPartialUpdateData = {
    body?: PatchedTaskWritable;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}/';
};

export type TasksPartialUpdateResponses = {
    200: Task;
};

export type TasksPartialUpdateResponse = TasksPartialUpdateResponses[keyof TasksPartialUpdateResponses];

export type TasksUpdateData = {
    body: TaskWritable;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}/';
};

export type TasksUpdateResponses = {
    200: Task;
};

export type TasksUpdateResponse = TasksUpdateResponses[keyof TasksUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersListResponses = {
    200: Array<User>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersGoogleCallbackRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/google/callback/';
};

export type UsersGoogleCallbackRetrieveResponses = {
    200: User;
};

export type UsersGoogleCallbackRetrieveResponse = UsersGoogleCallbackRetrieveResponses[keyof UsersGoogleCallbackRetrieveResponses];

export type UsersGoogleInitiateRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/google/initiate/';
};

export type UsersGoogleInitiateRetrieveResponses = {
    200: User;
};

export type UsersGoogleInitiateRetrieveResponse = UsersGoogleInitiateRetrieveResponses[keyof UsersGoogleInitiateRetrieveResponses];

export type UsersLogoutCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/logout/';
};

export type UsersLogoutCreateResponses = {
    200: User;
};

export type UsersLogoutCreateResponse = UsersLogoutCreateResponses[keyof UsersLogoutCreateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: User;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];
