// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { completionsCreate, completionsDestroy, completionsList, completionsPartialUpdate, completionsRetrieve, completionsUpdate, type Options, schemaRetrieve, streaksCreate, streaksDestroy, streaksList, streaksPartialUpdate, streaksRetrieve, streaksUpdate } from '../sdk.gen';
import type { CompletionsCreateData, CompletionsCreateResponse, CompletionsDestroyData, CompletionsDestroyResponse, CompletionsListData, CompletionsListResponse, CompletionsPartialUpdateData, CompletionsPartialUpdateResponse, CompletionsRetrieveData, CompletionsRetrieveResponse, CompletionsUpdateData, CompletionsUpdateResponse, SchemaRetrieveData, SchemaRetrieveResponse, StreaksCreateData, StreaksCreateResponse, StreaksDestroyData, StreaksDestroyResponse, StreaksListData, StreaksListResponse, StreaksPartialUpdateData, StreaksPartialUpdateResponse, StreaksRetrieveData, StreaksRetrieveResponse, StreaksUpdateData, StreaksUpdateResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const completionsListQueryKey = (options?: Options<CompletionsListData>) => createQueryKey('completionsList', options);

export const completionsListOptions = (options?: Options<CompletionsListData>) => queryOptions<CompletionsListResponse, DefaultError, CompletionsListResponse, ReturnType<typeof completionsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await completionsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: completionsListQueryKey(options)
});

export const completionsCreateMutation = (options?: Partial<Options<CompletionsCreateData>>): UseMutationOptions<CompletionsCreateResponse, DefaultError, Options<CompletionsCreateData>> => {
    const mutationOptions: UseMutationOptions<CompletionsCreateResponse, DefaultError, Options<CompletionsCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completionsCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const completionsDestroyMutation = (options?: Partial<Options<CompletionsDestroyData>>): UseMutationOptions<CompletionsDestroyResponse, DefaultError, Options<CompletionsDestroyData>> => {
    const mutationOptions: UseMutationOptions<CompletionsDestroyResponse, DefaultError, Options<CompletionsDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completionsDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const completionsRetrieveQueryKey = (options: Options<CompletionsRetrieveData>) => createQueryKey('completionsRetrieve', options);

export const completionsRetrieveOptions = (options: Options<CompletionsRetrieveData>) => queryOptions<CompletionsRetrieveResponse, DefaultError, CompletionsRetrieveResponse, ReturnType<typeof completionsRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await completionsRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: completionsRetrieveQueryKey(options)
});

export const completionsPartialUpdateMutation = (options?: Partial<Options<CompletionsPartialUpdateData>>): UseMutationOptions<CompletionsPartialUpdateResponse, DefaultError, Options<CompletionsPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<CompletionsPartialUpdateResponse, DefaultError, Options<CompletionsPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completionsPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const completionsUpdateMutation = (options?: Partial<Options<CompletionsUpdateData>>): UseMutationOptions<CompletionsUpdateResponse, DefaultError, Options<CompletionsUpdateData>> => {
    const mutationOptions: UseMutationOptions<CompletionsUpdateResponse, DefaultError, Options<CompletionsUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completionsUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const schemaRetrieveQueryKey = (options?: Options<SchemaRetrieveData>) => createQueryKey('schemaRetrieve', options);

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieveOptions = (options?: Options<SchemaRetrieveData>) => queryOptions<SchemaRetrieveResponse, DefaultError, SchemaRetrieveResponse, ReturnType<typeof schemaRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await schemaRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: schemaRetrieveQueryKey(options)
});

export const streaksListQueryKey = (options?: Options<StreaksListData>) => createQueryKey('streaksList', options);

export const streaksListOptions = (options?: Options<StreaksListData>) => queryOptions<StreaksListResponse, DefaultError, StreaksListResponse, ReturnType<typeof streaksListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streaksList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streaksListQueryKey(options)
});

export const streaksCreateMutation = (options?: Partial<Options<StreaksCreateData>>): UseMutationOptions<StreaksCreateResponse, DefaultError, Options<StreaksCreateData>> => {
    const mutationOptions: UseMutationOptions<StreaksCreateResponse, DefaultError, Options<StreaksCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await streaksCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const streaksDestroyMutation = (options?: Partial<Options<StreaksDestroyData>>): UseMutationOptions<StreaksDestroyResponse, DefaultError, Options<StreaksDestroyData>> => {
    const mutationOptions: UseMutationOptions<StreaksDestroyResponse, DefaultError, Options<StreaksDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await streaksDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const streaksRetrieveQueryKey = (options: Options<StreaksRetrieveData>) => createQueryKey('streaksRetrieve', options);

export const streaksRetrieveOptions = (options: Options<StreaksRetrieveData>) => queryOptions<StreaksRetrieveResponse, DefaultError, StreaksRetrieveResponse, ReturnType<typeof streaksRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await streaksRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: streaksRetrieveQueryKey(options)
});

export const streaksPartialUpdateMutation = (options?: Partial<Options<StreaksPartialUpdateData>>): UseMutationOptions<StreaksPartialUpdateResponse, DefaultError, Options<StreaksPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<StreaksPartialUpdateResponse, DefaultError, Options<StreaksPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await streaksPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const streaksUpdateMutation = (options?: Partial<Options<StreaksUpdateData>>): UseMutationOptions<StreaksUpdateResponse, DefaultError, Options<StreaksUpdateData>> => {
    const mutationOptions: UseMutationOptions<StreaksUpdateResponse, DefaultError, Options<StreaksUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await streaksUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
